import java.security.MessageDigest

// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.compose) apply false
}

val openApiGeneratorCli by configurations.creating

dependencies {
    openApiGeneratorCli("org.openapitools:openapi-generator-cli:7.15.0")
}

val contractSnapshot = layout.projectDirectory.file("contracts/backend-openapi-v1.yaml")
val siblingBackendOpenApi = layout.projectDirectory.file("../foodmind-backend/src/main/resources/openapi/openapi.yaml")
val backendOpenApi = file(
    providers.environmentVariable("FOODMIND_BACKEND_OPENAPI").orNull
        ?: siblingBackendOpenApi.asFile.takeIf { it.isFile }?.absolutePath
        ?: contractSnapshot.asFile.absolutePath,
)
val contractLock = layout.projectDirectory.file("contracts/backend-openapi-v1.lock")
val generatedManifest = layout.projectDirectory.file(
    "app/src/main/java/com/foodmind/foodmind_android/core/network/generated/BackendOpenApiContract.kt",
)

fun String.canonicalText(): String = replace("\r\n", "\n").replace("\r", "\n")

fun String.sha256(): String = MessageDigest.getInstance("SHA-256")
    .digest(canonicalText().toByteArray(Charsets.UTF_8))
    .joinToString("") { "%02x".format(it) }

fun operations(openApi: String): Set<String> {
    val methods = setOf("get", "post", "put", "patch", "delete", "head", "options")
    var currentPath: String? = null
    return buildSet {
        openApi.lineSequence().forEach { line ->
            Regex("^  (/[^:]+):\\s*$").matchEntire(line)?.let {
                currentPath = it.groupValues[1]
                return@forEach
            }
            Regex("^    ([a-z]+):\\s*$").matchEntire(line)?.let {
                val method = it.groupValues[1]
                if (currentPath != null && method in methods) add("${method.uppercase()} $currentPath")
            }
        }
    }
}

fun schemaProperties(openApi: String): Map<String, Set<String>> {
    var inSchemas = false
    var currentSchema: String? = null
    var inProperties = false
    val result = linkedMapOf<String, MutableSet<String>>()
    openApi.lineSequence().forEach { line ->
        if (line == "  schemas:") {
            inSchemas = true
            return@forEach
        }
        if (!inSchemas) return@forEach
        Regex("^    ([A-Za-z0-9_]+):\\s*$").matchEntire(line)?.let {
            currentSchema = it.groupValues[1]
            result.getOrPut(currentSchema!!) { linkedSetOf() }
            inProperties = false
            return@forEach
        }
        if (line == "      properties:") {
            inProperties = true
            return@forEach
        }
        if (inProperties) {
            Regex("^        ([A-Za-z0-9_]+):\\s*$").matchEntire(line)?.let {
                result.getValue(currentSchema!!).add(it.groupValues[1])
                return@forEach
            }
            if (Regex("^      \\S").containsMatchIn(line)) inProperties = false
        }
    }
    return result.mapValues { it.value.toSet() }
}

fun generatedContract(openApi: String): String {
    val operationLines = operations(openApi).sorted().joinToString(",\n") { "        \"$it\"" }
    val schemas = schemaProperties(openApi).entries
        .filter { it.value.isNotEmpty() }
        .sortedBy { it.key }
        .joinToString(",\n") { (name, fields) ->
            "        \"$name\" to setOf(${fields.sorted().joinToString(", ") { "\"$it\"" }})"
        }
    return """// Generated by ./gradlew apiGenerate. Do not edit.
package com.foodmind.foodmind_android.core.network.generated

internal object BackendOpenApiContract {
    const val SHA256 = "${openApi.sha256()}"
    val operations = setOf(
$operationLines,
    )
    val schemaFields = mapOf(
$schemas,
    )
}
"""
}

tasks.register("apiGenerateContract") {
    group = "verification"
    description = "Snapshots the backend OpenAPI source and generates Android contract metadata."
    notCompatibleWithConfigurationCache("Contract generation uses the checked-out sibling backend source.")
    inputs.file(backendOpenApi)
    outputs.files(contractSnapshot, contractLock, generatedManifest)
    doLast {
        val source = backendOpenApi.readText().canonicalText()
        contractSnapshot.asFile.apply { parentFile.mkdirs(); writeText(source) }
        generatedManifest.asFile.apply { parentFile.mkdirs(); writeText(generatedContract(source)) }
        contractLock.asFile.writeText("sha256=${source.sha256()}\noperations=${operations(source).size}\n")
    }
}

tasks.register<JavaExec>("apiGenerate") {
    group = "verification"
    description = "Generates reference Kotlin Retrofit APIs and models from the canonical backend OpenAPI."
    notCompatibleWithConfigurationCache("OpenAPI Generator consumes a sibling-repository contract snapshot.")
    dependsOn("apiGenerateContract")
    classpath = openApiGeneratorCli
    mainClass.set("org.openapitools.codegen.OpenAPIGenerator")
    args(
        "generate",
        "-g", "kotlin",
        "-i", contractSnapshot.asFile.absolutePath.replace('\\', '/'),
        "-o", layout.buildDirectory.dir("generated/openapi").get().asFile.absolutePath,
        "--library", "jvm-retrofit2",
        "--additional-properties", "packageName=com.foodmind.contract,apiPackage=com.foodmind.contract.api,modelPackage=com.foodmind.contract.model,serializationLibrary=gson,useCoroutines=true",
    )
}

tasks.register("apiCoverage") {
    group = "verification"
    description = "Requires Retrofit to declare every backend OpenAPI operation exactly once."
    notCompatibleWithConfigurationCache("Coverage reads and compares checked-in source files.")
    mustRunAfter("apiGenerateContract")
    inputs.files(contractSnapshot, "app/src/main/java/com/foodmind/foodmind_android/core/network/FoodMindApi.kt")
    doLast {
        val expected = operations(contractSnapshot.asFile.readText())
        val retrofitSource = file("app/src/main/java/com/foodmind/foodmind_android/core/network/FoodMindApi.kt").readText()
        val actual = Regex("@(GET|POST|PUT|PATCH|DELETE)\\(\"([^\"]+)\"\\)")
            .findAll(retrofitSource)
            .map { match ->
                val path = match.groupValues[2].trimStart('/')
                "${match.groupValues[1]} /$path"
            }
            .toList()
        val duplicates = actual.groupingBy { it }.eachCount().filterValues { it != 1 }
        val missing = expected - actual.toSet()
        val extra = actual.toSet() - expected
        check(missing.isEmpty() && extra.isEmpty() && duplicates.isEmpty()) {
            "Android API coverage drift. Missing=$missing Extra=$extra Duplicates=$duplicates"
        }
        check(expected.size == 86) { "Expected the release contract to contain 86 operations, found ${expected.size}." }
        logger.lifecycle("Android API coverage passed: ${expected.size}/86 operations, no duplicates.")
    }
}

tasks.register("apiCheck") {
    group = "verification"
    description = "Fails when the backend snapshot, generated metadata, or DTO schema manifest drifts."
    notCompatibleWithConfigurationCache("Contract checks compare sibling-repository and generated files.")
    mustRunAfter("apiGenerateContract")
    dependsOn("apiCoverage")
    inputs.files(backendOpenApi, contractSnapshot, contractLock, generatedManifest)
    doLast {
        val source = backendOpenApi.readText()
        val snapshot = contractSnapshot.asFile.readText()
        check(source.canonicalText() == snapshot.canonicalText()) {
            "Android OpenAPI snapshot differs from the backend source. Run ./gradlew apiGenerate."
        }
        check(contractLock.asFile.readText().canonicalText() == "sha256=${snapshot.sha256()}\noperations=${operations(snapshot).size}\n") {
            "Android OpenAPI lock is stale. Run ./gradlew apiGenerate."
        }
        check(generatedManifest.asFile.readText().canonicalText() == generatedContract(snapshot).canonicalText()) {
            "Android generated contract metadata is stale. Run ./gradlew apiGenerate."
        }
        logger.lifecycle("Android API source, lock, generated DTO manifest, and Retrofit coverage match.")
    }
}

subprojects {
    tasks.matching { it.name == "check" }.configureEach {
        dependsOn(rootProject.tasks.named("apiCheck"))
    }
}
